Now stores skills as enums, can process multiple characters
Kevdog25/DNDRoller pull request #2
Opened 2019-01-01 03:47 UTC by maliceholmes

2019-01-01 17:00 UTC, kpwelsh requested changes

2019-01-01 17:00 UTC, kpwelsh commented on Character.py
> +def getEnum(name):
See Enum documentation
https://docs.python.org/3/library/enum.html#programmatic-access-to-enumeration-members-and-their-attributes

2019-01-01 17:14 UTC, maliceholmes commented on Character.py
> +def getEnum(name):
fixed

2019-01-02 02:04 UTC, Kevdog25 commented on Character.py
> +def getEnum(name):
can you get rid of this function then?

2019-01-12 02:36 UTC, closed without merging

2019-01-12 02:37 UTC, Kevdog25 commented
I put this in when making other changes.